### ISSUE TITLE
Analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

### ISSUE THREAD

**Issue by avii-07** [Recode-Hive/Stackoverflow-Analysis#103]
**Is your feature request related to a problem? Please describe.**
Analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

**Describe the solution you'd like**
I will be using the required data visualization techniques to solve this problem.

**Describe alternatives you've considered**
I believe the better way would be only to use data visualization techniques.

**Additional context**
Other features that can be used are Overtime and country to analyze salary and gender inequalities.

What problem is this feature trying to solve?
Analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

How do we know when the feature is complete?
I will be sending a PR request in 3-4 days after the task assigned to me.

**Comment by okaditya84** [comment]
Kindly give more insights on which year dataset you want to analyze and what methods will you be using.

**Comment by avii-07** [comment]
@okaditya84 
I would like to analyze the 2020 year dataset. 

I will be using matplotlib and seaborn libraries plots such as bar plots , box plot , scatter plots.
Correlation matrix , heatmap.
Feature importance using Lightgbm regression for salary. 
Probability distribution functions for continous variables such as coding experience and salary. 

These are some of the methods I will be using.  
Please assign me this issue. 

Thank you..

**Comment by barlasanjay** [comment]
Could you please assign the labels for this issue sir?

**Comment by barlasanjay** [comment]
**Is your feature request related to a problem? Please describe.**
My goal is to understand and analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

**Describe the solution you'd like**
I have a solution that utilizes both statistical analysis and data visualization techniques to thoroughly understand and analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

**Tasks todo to achieve this:**

- [ ]  Data Collection
- [ ] Data Preparation and Cleaning
- [ ] Exploratory Data Analysis (EDA)
- [ ] Statistical Analysis
- [ ] Data Visualization
- [ ] Gender Inequality Analysis
- [ ] Interpretation and Insights

**What problem is this feature trying to solve?**
My proposal will surely analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.

**How do we know when the feature is complete?**
I will update the list of todo everyday

**Comment by okaditya84** [comment]
> @okaditya84 I would like to analyze the 2020 year dataset.
> 
> I will be using matplotlib and seaborn libraries plots such as bar plots , box plot , scatter plots. Correlation matrix , heatmap. Feature importance using Lightgbm regression for salary. Probability distribution functions for continous variables such as coding experience and salary.
> 
> These are some of the methods I will be using. Please assign me this issue.
> 
> Thank you..

Kindly check if the issue is already assigned and added. Additionally, if the issue is not assigned to anyone, create an issue with the latest issue template (check contribution.md)

**Comment by sanjay-kv** [comment]
> **Is your feature request related to a problem? Please describe.** My goal is to understand and analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.
> 
> **Describe the solution you'd like** I have a solution that utilizes both statistical analysis and data visualization techniques to thoroughly understand and analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.
> 
> **Tasks todo to achieve this:**
> 
> * [ ]   Data Collection
> * [ ]  Data Preparation and Cleaning
> * [ ]  Exploratory Data Analysis (EDA)
> * [ ]  Statistical Analysis
> * [ ]  Data Visualization
> * [ ]  Gender Inequality Analysis
> * [ ]  Interpretation and Insights
> 
> **What problem is this feature trying to solve?** My proposal will surely analyze the impact of higher education, experience, and responsibilities on salary and gender inequalities.
> 
> **How do we know when the feature is complete?** I will update the list of todo everyday

These all issues has been already analysed closing the issue for the same reason
